- Q1. Differentiate between a Class and an Object with a Real-World Example?

### Class

- A class is a blueprint or template used to create objects. It defines the attributes (variables) and behaviors (methods) that the objects will have.

### Object

An object is a real instance of a class. It contains actual values and can perform the actions defined in the class.

### Real-World Example

Imagine a Car.

**Class:** Car (Blueprint)
**Objects:** Honda Civic, Toyota Corolla, BMW X5

The class defines common properties like:

- Color
- Model
- Speed

Each object has its own values.

Example


# EDA IN PYTHON (WEEK 04 )  DAY 03 )#)


In [4]:
pip install numpy pandas matplotlib seaborn


Note: you may need to restart the kernel to use updated packages.


In [7]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Time stamp
import time
print(f"Last Update: {time.asctime()}")

# Filter warnings
import warnings as w
w.filterwarnings("ignore")

Last Update: Wed Jul 22 09:47:19 2026


# UNDERSTANNDING NUMPY FUNDAMENTALS 

### LEVEL 3

# CREATING AN ARRAY 

In [8]:
arr =  np.array([3,4,5,3,5,9,5])
arr

array([3, 4, 5, 3, 5, 9, 5])

In [9]:
type(arr)

numpy.ndarray

In [11]:
a = np.array([1,2,3,4,5])
a.ndim

1

In [17]:
import numpy as np

ab = np.array([
    [1, 2, 3, 4, 5],
    [1, 2, 3, 43, 2]
])

print(ab)
print(ab.ndim)

[[ 1  2  3  4  5]
 [ 1  2  3 43  2]]
2


In [20]:
import numpy as np

ab = np.array([
    [1, 2, 3, 4, 5,3,4],
    [1, 2, 3, 43, 2,5,3],
   
])

print(ab)
print(ab.ndim)

[[ 1  2  3  4  5  3  4]
 [ 1  2  3 43  2  5  3]]
2


In [24]:


c = np.array([
    [
        [1,2,3,4],
        [3,4,5,6]
    ],

    [
        [1,2,3,4],
        [5,6,8,9]
    ]
])

print(c)
print("Dimensions:", c.ndim)
print("Shape:", c.shape)

            

[[[1 2 3 4]
  [3 4 5 6]]

 [[1 2 3 4]
  [5 6 8 9]]]
Dimensions: 3
Shape: (2, 2, 4)


In [34]:
# (2,3,5) shaps 3D array
import numpy as np

d = np.array([
    [
        [1, 2, 3,87,6],
        [34, 5, 6,65,8],
        [43, 45, 6,65,66]
    ],
    [
        [1, 2, 3,7,7],
        [34, 5, 6,45,5],
        [54, 5, 6,4,5]
    ]
])

print(d)
print("Dimensions:", d.ndim)
print("Shape:", d.shape)
print("Shape:", d.size)


[[[ 1  2  3 87  6]
  [34  5  6 65  8]
  [43 45  6 65 66]]

 [[ 1  2  3  7  7]
  [34  5  6 45  5]
  [54  5  6  4  5]]]
Dimensions: 3
Shape: (2, 3, 5)
Shape: 30


In [37]:
e = np.array(
    [3,4,5,6,56,55,4,44,33,44,55,66,77,65,66,55]
)
e, e.dim

AttributeError: 'numpy.ndarray' object has no attribute 'dim'

# ARRAY OPERATIONS 

In [38]:
a = [1,2,3]
b = [4,6,7]
a + b

[1, 2, 3, 4, 6, 7]

In [45]:
a= np.array([1,2,3,4])
b = np.array([4,3,9,2])
print("sum" ,a+b)
print("substract" ,a-b)
print(a/b)

print(a%b)
print(a//b)
print(a%b)
print(a<b)
print(a>b)
print(a<=b)
print(a>=b)



sum [ 5  5 12  6]
substract [-3 -1 -6  2]
[0.25       0.66666667 0.33333333 2.        ]
[1 2 3 0]
[0 0 0 2]
[1 2 3 0]
[ True  True  True False]
[False False False  True]
[ True  True  True False]
[False False False  True]


## USEFULL FUNCTIONS IN NUMPY 

In [51]:
x = np.zeros((10,10) ,dtype= 'int')
x

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [56]:
y = np.ones((5,10), dtype='int')
y*4

array([[4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4, 4, 4, 4]])

In [57]:
np.eye(12, dtype='int')

array([[1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1]])

In [58]:
np.arange(1,20,3)

array([ 1,  4,  7, 10, 13, 16, 19])

In [62]:
np.linspace(0,10,20 ,dtype='float')

array([ 0.        ,  0.52631579,  1.05263158,  1.57894737,  2.10526316,
        2.63157895,  3.15789474,  3.68421053,  4.21052632,  4.73684211,
        5.26315789,  5.78947368,  6.31578947,  6.84210526,  7.36842105,
        7.89473684,  8.42105263,  8.94736842,  9.47368421, 10.        ])

In [67]:
n=p.reshape(250,20)
n

array([[0.00000000e+00, 2.00040008e-02, 4.00080016e-02, ...,
        3.40068014e-01, 3.60072014e-01, 3.80076015e-01],
       [4.00080016e-01, 4.20084017e-01, 4.40088018e-01, ...,
        7.40148030e-01, 7.60152030e-01, 7.80156031e-01],
       [8.00160032e-01, 8.20164033e-01, 8.40168034e-01, ...,
        1.14022805e+00, 1.16023205e+00, 1.18023605e+00],
       ...,
       [9.88197640e+01, 9.88397680e+01, 9.88597720e+01, ...,
        9.91598320e+01, 9.91798360e+01, 9.91998400e+01],
       [9.92198440e+01, 9.92398480e+01, 9.92598520e+01, ...,
        9.95599120e+01, 9.95799160e+01, 9.95999200e+01],
       [9.96199240e+01, 9.96399280e+01, 9.96599320e+01, ...,
        9.99599920e+01, 9.99799960e+01, 1.00000000e+02]], shape=(250, 20))

# random choice 

In [70]:
d=n.reshape(5,2,1,1,2,1,5,2,5,5)

In [73]:
colors =['red', 'green ', 'blue', 'white', 'black']
np.random.choice(colors,5)
         

array(['red', 'red', 'black', 'white', 'white'], dtype='<U6')

# random seed 

In [80]:
np.random.seed(12)
np.random.randint(8,32,(12,43,3))

array([[[19, 14, 25],
        [10, 11, 11],
        [20, 24, 30],
        ...,
        [11, 15, 27],
        [30, 25, 12],
        [22, 18, 20]],

       [[27, 16, 16],
        [30, 17, 22],
        [12, 23, 12],
        ...,
        [25, 29,  8],
        [14, 29, 14],
        [12, 31, 16]],

       [[31,  9, 26],
        [26, 15,  8],
        [25,  8, 29],
        ...,
        [16, 31, 28],
        [10, 19, 26],
        [27, 22, 27]],

       ...,

       [[21, 14, 31],
        [16, 25, 12],
        [23, 30, 20],
        ...,
        [14,  9, 17],
        [23, 15, 12],
        [24, 19, 17]],

       [[31, 14, 18],
        [29, 13, 14],
        [14, 16, 29],
        ...,
        [19, 15, 18],
        [ 9, 22, 20],
        [23, 27, 16]],

       [[28, 28, 30],
        [26, 24, 24],
        [16, 12, 19],
        ...,
        [12, 23, 25],
        [26, 24, 29],
        [19, 12, 24]]], shape=(12, 43, 3), dtype=int32)

## stats in numpy 

In [91]:

print(a.min(),a.max())

1 4


In [85]:
a

array([1, 2, 3, 4])

In [92]:
print(a.sum())

10


In [93]:
len(a)

4

In [114]:
print("-"*50)
print(f"{"Mean , Median , Mode":^50}")
print("-"*50)
print(f"{"min":<30} = {np.min(a)}")
print(f"{"max":<30} = {np.max(a)}")
print(f"{"mean":<30} = {np.mean(a)}")
print(f"{"median":<30} = {np.median(a)}")
print(f"{"variance":<30} = {np.var(a):.1f}")
# print(f"{"Quartiles":<30} = {np.percentile(,[0,25,50,75,100])}")


SyntaxError: f-string: expecting '=', or '!', or ':', or '}' (2219123982.py, line 9)